"use client";
import { useState, useEffect } from "react";
import { useTranslation } from "react-i18next";
import { loadTranslations } from "../utils/i18n";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { usePathname } from "next/navigation";
import { AuthProvider } from "../context/authContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const { i18n } = useTranslation();
  const [isLoading, setIsLoading] = useState(true);
  const pathname = usePathname();

  useEffect(() => {
    const initializeTranslations = async () => {
      await loadTranslations(i18n.language || "en");
      setIsLoading(false);
    };

    initializeTranslations();
  }, [i18n.language]);

  const isAuthRoute = ["/admin", "/teacher", "/student", "/auth"].some((path) =>
    pathname.startsWith(path)
  );

  if (isLoading) {
    return <div>Loading...</div>;
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          {!isAuthRoute && <Navbar />}
          {children}
          {!isAuthRoute && <Footer />}
        </AuthProvider>
      </body>
    </html>
  );
}
