"use client";
import { useEffect } from "react";
import { useTranslation } from "react-i18next";
import { loadTranslations } from "../utils/i18n"
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const { i18n } = useTranslation();
  useEffect(() => {
    const initializeTranslations = async () => {
      await loadTranslations(i18n.language || 'en');
    };

    initializeTranslations();
  }, [i18n.language]);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
          <Navbar />
          {children}
          <Footer />
        
      </body>
    </html>
  );
}
